//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int ID { get; set; }
        public string ADI { get; set; }
        public string E_MAIL { get; set; }
        public string USERNAME { get; set; }
        public string SIFRE { get; set; }
        public bool YETKI { get; set; }
    }
}
