//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDIRIM
    {
        public int ID { get; set; }
        public Nullable<int> MARKAID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<byte> INDIRIMYUZDESI { get; set; }
        public Nullable<System.DateTime> BASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> BITISTARIHI { get; set; }
    }
}
