//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OyuncakciEntities : DbContext
    {
        public OyuncakciEntities()
            : base("name=OyuncakciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMIN { get; set; }
        public DbSet<ALTKATEGORI> ALTKATEGORI { get; set; }
        public DbSet<BAGIS> BAGIS { get; set; }
        public DbSet<BAGISYAPILACAKYERLER> BAGISYAPILACAKYERLER { get; set; }
        public DbSet<CANLIDESTEK> CANLIDESTEK { get; set; }
        public DbSet<FAVORILER> FAVORILER { get; set; }
        public DbSet<FIYATIDUSUNCEHABERVER> FIYATIDUSUNCEHABERVER { get; set; }
        public DbSet<INDIRIM> INDIRIM { get; set; }
        public DbSet<KAMPANYADANHABERDAROL> KAMPANYADANHABERDAROL { get; set; }
        public DbSet<KATEGORI> KATEGORI { get; set; }
        public DbSet<MARKA> MARKA { get; set; }
        public DbSet<SEPETIM> SEPETIM { get; set; }
        public DbSet<SEPETLER> SEPETLER { get; set; }
        public DbSet<SIFREMIYENILE> SIFREMIYENILE { get; set; }
        public DbSet<SIPARISLERIM> SIPARISLERIM { get; set; }
        public DbSet<SIPARISTAKIPTABLOSU> SIPARISTAKIPTABLOSU { get; set; }
        public DbSet<URUN> URUN { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<YASARALIK> YASARALIK { get; set; }
        public DbSet<YORUM> YORUM { get; set; }
    }
}
