//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIFREMIYENILE
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string YENILEMEKODU { get; set; }
    }
}
