//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISLERIM
    {
        public int ID { get; set; }
        public Nullable<int> SEPETLERID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> ONAYLANDIMI { get; set; }
        public Nullable<bool> IPTAL { get; set; }
    }
}
