//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oyuncakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID { get; set; }
        public string ADİ { get; set; }
        public string SOYADİ { get; set; }
        public string E_MAİL { get; set; }
        public string SIFRE { get; set; }
        public bool CINSIYET { get; set; }
        public string CEPTELNO { get; set; }
        public Nullable<bool> MAILLISTESI { get; set; }
        public Nullable<bool> UYELIKSOZLESMESI { get; set; }
        public bool KISISELVERILERINKORUNMASI { get; set; }
    }
}
